### ISSUE TITLE
Highlighting issue when creating new objects as part of a method call

### ISSUE THREAD

**Issue by quanticle** [OrangeT/vim-csharp#28]
With the following example code

```
namespace Test 
{

    internal static class Foo
    {
        public static Collection<SomeObjectType> AMethod(int param1, string param2)
        {
            string intermediateVal = DoSomething(param1, param2);
            return Foo.blah(param1,
                new Object1(),
                new Object2());
        }
    }
}
```

I notice that the `new` in front of `Object1()` isn't getting highlighted, but the `new` in front of `Object2()` is. I've attached a screenshot below that demonstrates the issue. The difference in formatting remains regardless of the colorscheme selected, which makes me think that it's an issue with the cs.vim syntax definition file. That said, I'm completely new to how vim syntax definitions work, so I'm not exactly sure where to go from here in debugging this.
![vim-cs-highlighting-error](https://cloud.githubusercontent.com/assets/122136/7241237/4e3b7756-e76c-11e4-8e41-cfea14c7ff2f.png)

**Comment by kianryan** [comment]
Issue now resolved
