### ISSUE TITLE
"in" keyword not being highlighted. 

### ISSUE THREAD

**Issue by OskarSigvardsson** [OrangeT/vim-csharp#33]
I've been noticing that the "in" keyword in foreach-loops isn't highlighting properly in my vim. All other keywords (as far as I've seen) works just fine except for in. Here's an image showing what I mean: 

![screenshot](https://cloud.githubusercontent.com/assets/7059777/10279504/7e56d542-6b66-11e5-9834-9587ed027230.png)

See what I mean? "in" should be green or orange or something. I'm using MacVim and the Solarized Light color scheme, if that makes any difference. 

I checked the source and saw that "in" was listed in syntax/cs.vim under "csUnspecifiedStatement", just like "as" is, and "as" highlights just fine, so I have no idea what's causing it, or if it's a widespread problem or just happens to me. 

It's not the most urgent fix in the universe, but it bugs me every I see it, so I figured I'd post here :)

**Comment by kianryan** [comment]
Hi, please see latest commits, this should now be supported.

**Comment by OskarSigvardsson** [comment]
Indeed, seems to work fine now. Thanks!
