### ISSUE TITLE
Ability to Fold Methods

### ISSUE THREAD

**Issue by austincrft** [OrangeT/vim-csharp#36]
I am a big fan of folding in Vim. The existing region folding is nice, but I don't use a lot of regions in my code. In Visual Studio, I frequently used the "Outlining -> Collapse to Definitions" feature to get a higher-level architectural view of a class.

Would you be opposed to including more advanced folding in this syntax definition? I'm willing to put in the work for it so long as you think it's within the scope of this project.

I was thinking something along the lines of this:

```
+---- 3 lines: public void FooBar()-----------------------------------------------
```

**Comment by andywatts** [comment]
FWIW I get good results with `:set syntax=cpp`

**Comment by austincrft** [comment]
I just started using `:set foldmethod=indent`. It looks like this, but it's close enough.

```csharp
public void FooBar()
{
+---- 1 line: DoSomething()-----------------------------------------------
}
```
